Repository PipHarsveld/Hallo-Strandeiland, pull requests merged in 2023-06, with the labels that each got.

#40 💄 Updated padding header #39
  public/css/style.css
Labels: bug

#59 :art: Splitted CSS into multiple files
  public/css/detail-person.css
  public/css/detail-wish.css
  public/css/new-wish.css
  public/css/overview.css
  views/layouts/index.hbs
Labels: refactor

#70 🎨 Update the splitted CSS files
  public/css/detail-wish.css
  public/css/overview.css
  public/css/partials.css
  public/css/style.css
  public/scripts/script.js
  views/layouts/index.hbs
Labels: refactor

#74 :construction: Add page form for now
  package-lock.json
  package.json
  public/css/style.css
  public/images/houses_strandeiland.jpg
  public/images/map_of_strandeiland.jpg
  public/js/script.js
  router/routes.js
  server.js
  views/form.hbs
  views/layouts/index.hbs
Labels: enhancement

#73 ✨ Feature masonry grid
  public/css/overview.css
  public/css/style.css
  public/scripts/script.js
  views/layouts/index.hbs
  views/main.hbs
Labels: enhancement, musthave

#102 :lipstick: Fix cardwidth and margin bottom
  public/css/overview.css
  public/css/style.css
Labels: refactor

#69 ✨ Thema's toegevoegd aan filterBar
  data/themes.js
  public/css/new-wish.css
  public/css/overview.css
  public/css/partials.css
  public/css/style.css
  router/routes.js
  views/main.hbs
  views/partials/themeFilters.hbs
Labels: enhancement, refactor

#104 :boom: Wishes are being retrieved from API
  router/routes.js
Labels: enhancement

#110 :boom: Add themes from database to the wishcards
  data/wensen.js
  public/css/partials.css
  router/routes.js
  views/main.hbs
  views/partials/wishcard.hbs
Labels: enhancement, refactor

#127 ✨ Iteration wishcards and filterbar
  public/css/overview.css
  public/css/partials.css
  public/images/icon_ambassadeur.svg
  public/images/icon_reactions.svg
  public/images/icon_search.svg
  public/images/icon_sort.svg
  server.js
  views/main.hbs
  views/partials/wishcard.hbs
Labels: enhancement

#131 :boom: Make filters responsive
  public/css/overview.css
Labels: bug

#135 Console warnings
  public/css/overview.css
  public/css/style.css
  views/main.hbs
Labels: bug

#142 :bug: Fix database themaId to themeId
  router/routes.js
Labels: bug

#143 :bug: Fixed theme when new wish added
  router/routes.js
Labels: bug

#144 💡 Code comments
  public/css/new-wish.css
  public/css/overview.css
  router/routes.js
  server.js
  views/form.hbs
  views/main.hbs
  views/partials/wishcard.hbs
Labels: enhancement

#146 :bug: Fixed bug form not centered
  public/css/new-wish.css
Labels: bug

#147 Documentation code examples
  README.md
  router/routes.js
Labels: documentation
